name: Initialize Database After Deploy

on:
  workflow_run:
    workflows: ['Deploy'] # GitHub Actions에서 사용하는 배포 워크플로우 이름
    types:
      - completed

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Webhook
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_CY1GIYZNm2dxLxyVhnDc7Eql1Jqs/fCZUhGD6fF/api/initialize
        env:
          API_KEY: ${{ secrets.VERCEL_API_TOKEN }} # 필요 시 API 키 설정
