name: Initialize Database on Deploy Success

on:
  deployment_status:

jobs:
  initialize-database:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:
      - name: Initialize Database
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_CY1GIYZNm2dxLxyVhnDc7Eql1Jqs/adLgbm9F07/api/initialize
        env:
          API_KEY: ${{ secrets.VERCEL_API_TOKEN }}
