name: Initialize Database on Deploy Success

on:
  deployment_status:

jobs:
  initialize-database:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:
      - name: Initialize Database
        env:
          VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
        run: |
          curl -X POST https://culturewalk.vercel.app/map/api/initialize \
            -H "Authorization: Bearer $VERCEL_API_TOKEN"
