name: Initialize Database on Deploy Success

on:
  deployment_status:

jobs:
  initialize-database:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:
      - name: Initialize Database
        run: |
          curl -X POST https://culturewalk.vercel.app/api/initialize
        env:
          API_KEY: ${{ secrets.VERCEL_API_TOKEN }} # 필요 시 API 키 설정
