name: Scheduled Task

on:
  schedule:
    - cron: '0 22 * * *' # 매일 오후 10시에 실행

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel API
        env:
          VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
        run: |
          curl -X POST https://culturewalk.vercel.app/api/initialize \
            -H "Authorization: Bearer $VERCEL_API_TOKEN"
