name: Scheduled Task

on:
  schedule:
    - cron: '1 1 * * *' # 매일 UTC 오전 1시에 실행 (한국 시간 오후 10시)

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel API
        run: |
          curl -X POST https://culturewalk.vercel.app/api/initialize
